[package]
name = "gui_iced"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.10", features = ["canvas", "tokio", "image", "advanced"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tiff = "0.9"
image = "0.24"
anyhow = "1.0"


